spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loginapp?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: dialect:org.hibernate.dialect.MySQL5Dialect
  server:
    error:
      whitelabel:
        enabled:false